In [19]:
import zipfile
import pandas as pd

# open zipped voyages dataset
with zipfile.ZipFile("voyages_202301.csv.zip") as z:
   # open the csv file in the dataset
   with z.open("voyages_202301.csv") as f:
       
      # read the dataset
        voyages_df = pd.read_csv(f)

        
#read in vessels dataset
vessels_df = pd.read_csv('fishing-vessels-v2.csv')


#read in anchorages dataset
anchorages_df = pd.read_csv('named_anchorages_v2_20221206.csv')

/var/folders/ng/41b1kp4n0wg3hvfwdd1fdzzm0000gn/T/ipykernel_59337/695393304.py:18: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  anchorages_df = pd.read_csv('named_anchorages_v2_20221206.csv')

,mmsi,flag_ais,flag_registry,flag_gfw,vessel_class_inferred,vessel_class_inferred_score,vessel_class_registry,vessel_class_gfw,self_reported_fishing_vessel,length_m_inferred,...,registries_listed,fishing_hours_2012,fishing_hours_2013,fishing_hours_2014,fishing_hours_2015,fishing_hours_2016,fishing_hours_2017,fishing_hours_2018,fishing_hours_2019,fishing_hours_2020
0,40120000,NaN,GRC,GRC,NaN,NaN,trawlers,trawlers,True,NaN,...,EU|GFCM|IMO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,674.10
1,444002410,NaN,KOR,KOR,NaN,NaN,tuna_purse_seines,tuna_purse_seines,False,NaN,...,FFA|IMO|ISSF|KOR|WCPFC|WCPFC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,144.43
2,987654320,NaN,PHL,PHL,NaN,NaN,tuna_purse_seines,tuna_purse_seines,False,NaN,...,FFA|ISSF|WCPFC|WCPFC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,545.33
3,554128120,NaN,NRU,NRU,NaN,NaN,tuna_purse_seines,tuna_purse_seines,False,NaN,...,FFA|IMO|ISSF|TWN4|WCPFC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,587.01
4,112119600,NaN,USA,USA,NaN,NaN,fishing,fishing,True,NaN,...,IMO|USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,318.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114186,601523000,ZAF,NaN,ZAF,other_purse_seines,0.999,NaN,other_purse_seines,True,29.29,...,NaN,NaN,NaN,NaN,225.17,248.62,276.68,268.53,138.34,309.70
114187,601554000,ZAF,NaN,ZAF,other_purse_seines,0.897,NaN,other_purse_seines,True,29.82,...,NaN,NaN,26.35,133.38,89.45,220.58,168.56,80.66,186.25,313.66
114188,601556000,ZAF,NaN,ZAF,other_purse_seines,0.764,NaN,other_purse_seines,True,33.97,...,NaN,NaN,61.26,87.62,154.18,155.50,217.70,140.74,203.67,220.57
114189,601039500,ZAF,NaN,ZAF,other_purse_seines,0.783,NaN,other_purse_seines,True,26.86,...,NaN,NaN,NaN,134.33,98.58,NaN,44.50,317.80,159.73,196.31
114190,601557000,ZAF,ZAF,ZAF,other_purse_seines,0.869,fishing,other_purse_seines,False,30.82,...,IMO,NaN,60.02,54.01,146.45,154.36,125.56,NaN,NaN,NaN

In [16]:
set(anchorages_df['dock'])

{False, True, nan}